---
- あいろんをかける
- あむ
- あやす
- いぬをつなげる
- いのる
- いれずみをいれる
- うく
- うたう
- うったえる
- うなずく
- うめく
- うめる
- えをかく
- おいかける
- おおきさをはかる
- おかねをはらう
- おこる
- おちる
- おふろにはいる
- およぐ
- かがやく
- かむ
- かわをなめす
- がむをかむ
- きすをする
- きめる
- きょうそうする
- きりきざむ
- くぎをうつ
- くすりをのむ
- くるまにのる
- けずる
- けっこんする
- けっとうする
- ける
- ころがる
- こわす
- こーどをかく
- ごうとうする
- さかだちする
- さける
- しばる
- じかんをはかる
- じまんする
- じゃまする
- じゅうどうする
- じゅうをうつ
- すわる
- せきをする
- そうじする
- そめる
- たべる
- ちゃんねるをかえる
- ちゅうゆする
- つかまえる
- つかまる
- つみあげる
- つる
- てらす
- てをふる
- てをあげる
- とうちゃくする
- なく
- なぐる
- なめる
- においをかぐ
- にらみつける
- ねむる
- のこぎりでひく
- はなす
- ばくはする
- ぱんとまいむする
- ひげをそる
- ひざまずく
- ひっこす
- ひやす
- ぴあのをひく
- ぴょんととぶ
- ふねをこぐ
- ほえる
- ほっけーをする
- ぽんとたたく
- まいあがる
- まがおになる
- まける
- まげる
- まもる
- まよう
- めをつぶる
- めをまわす
- めーるをかく
- もぐる
- ゆみをひく
- ようせつする
- よこたわる
- よごす
- らくがきする
- ろくおんする
- わらう
- わらわせる
