---
- いえ
- いんたーねっと
- うさぎ
- うし
- うま
- おうだんほどう
- おさら
- おーぷんかー
- おーろら
- かびん
- かぶとむし
- かめら
- きのこ
- きょうぎじょう
- きょうりゅう
- くし
- くっさくき
- くつ
- ぐんかん
- けーき
- げんきん
- こあら
- こうもり
- こっぷ
- こーひー
- さいころ
- さくらんぼ
- さすぺんだー
- さんぐらす
- しぇふ
- しーそー
- しーる
- じゃむ
- すず
- すのーぼーど
- すーつ
- すーぱー
- すーぷ
- せみ
- そうじき
- そふぁ
- そーせーじ
- たいや
- たいよう
- たおる
- たくしー
- たこ
- たばこ
- たまねぎ
- だんがん
- だんさー
- だーつ
- ちゅーば
- ちーず
- てつぱいぷ
- でんしんばしら
- でんわ
- とうふ
- とらっく
- どあのぶ
- どくへび
- なみ
- にっき
- にんぎょう
- ねこ
- のみ
- はち
- ばいく
- ばす
- ばっぐ
- ばら
- ひ
- ひかり
- ひこうき
- ひつじ
- ふくろう
- ふでばこ
- ぶらじゃー
- ぷれいすてーしょん
- へっどほん
- へるめっと
- べっど
- べんごし
- まじん
- まど
- まるた
- みいら
- みっと
- みずぎ
- むすびめ
- もうふ
- もも
- やね
- ゆき
- ゆみ
- ゆり
- りもこん
- れもん
- ろっこつ
- わいん
